version: '3.8'

services:
  cpp-env:
    build:
      context: .
      args:
      - uid=1001
      - gid=1001
      - username=abc
      - project_name=cppenv
    container_name: cpp-env
    image: cpp-env-image
    shm_size: '24gb'
    tty: true
    volumes: 
      - $PWD:/workspace
    command: '/bin/bash'
    ports:
      - 12301-12310:12301-12310